"""price change audit log

Revision ID: 378f713eaa95
Revises: 4b63ebec8de3
Create Date: 2025-12-09 05:10:06.932006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '378f713eaa95'
down_revision: Union[str, Sequence[str], None] = '4b63ebec8de3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_change_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('tipo_operacion', sa.Enum('compra', 'venta', name='tipo_operacion'), nullable=False),
    sa.Column('tipo_cliente', sa.Enum('regular', 'mayorista', 'menudeo', name='tipo_cliente'), nullable=False),
    sa.Column('old_precio_por_unidad', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('new_precio_por_unidad', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('old_version', sa.Integer(), nullable=True),
    sa.Column('new_version', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materiales.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_change_logs_id'), 'price_change_logs', ['id'], unique=False)
    op.create_index(op.f('ix_price_change_logs_material_id'), 'price_change_logs', ['material_id'], unique=False)
    op.create_index(op.f('ix_price_change_logs_user_id'), 'price_change_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_price_change_logs_user_id'), table_name='price_change_logs')
    op.drop_index(op.f('ix_price_change_logs_material_id'), table_name='price_change_logs')
    op.drop_index(op.f('ix_price_change_logs_id'), table_name='price_change_logs')
    op.drop_table('price_change_logs')
    # ### end Alembic commands ###
