"""materiales y tablas de precios

Revision ID: 4b63ebec8de3
Revises: b4bb996afed6
Create Date: 2025-12-09 04:40:21.188372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b63ebec8de3'
down_revision: Union[str, Sequence[str], None] = 'b4bb996afed6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('materiales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('unidad_medida', sa.String(length=50), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_materiales_id'), 'materiales', ['id'], unique=False)
    op.create_index(op.f('ix_materiales_nombre'), 'materiales', ['nombre'], unique=True)
    op.create_table('tablas_precios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('tipo_operacion', sa.Enum('compra', 'venta', name='tipo_operacion'), nullable=False),
    sa.Column('tipo_cliente', sa.Enum('regular', 'mayorista', 'menudeo', name='tipo_cliente'), nullable=False),
    sa.Column('precio_por_unidad', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('vigente_desde', sa.DateTime(), nullable=False),
    sa.Column('vigente_hasta', sa.DateTime(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materiales.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('material_id', 'tipo_operacion', 'tipo_cliente', 'version', name='uq_tabla_precio_material_tipo_version')
    )
    op.create_index(op.f('ix_tablas_precios_id'), 'tablas_precios', ['id'], unique=False)
    op.create_index(op.f('ix_tablas_precios_material_id'), 'tablas_precios', ['material_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tablas_precios_material_id'), table_name='tablas_precios')
    op.drop_index(op.f('ix_tablas_precios_id'), table_name='tablas_precios')
    op.drop_table('tablas_precios')
    op.drop_index(op.f('ix_materiales_nombre'), table_name='materiales')
    op.drop_index(op.f('ix_materiales_id'), table_name='materiales')
    op.drop_table('materiales')
    # ### end Alembic commands ###
